### ISSUE TITLE
Local tests are failing - 

### ISSUE THREAD

**Issue by rodowi** [mxabierto/shogun#30]
```bash
(shogun)➜  shogun git:(master) ✗ pip install -r dev-requirements.txt          
Downloading/unpacking Flask-Testing==0.4.2 (from -r dev-requirements.txt (line 1))
  Downloading Flask-Testing-0.4.2.tar.gz (40kB): 40kB downloaded
  Running setup.py egg_info for package Flask-Testing
```

```bash
(shogun)➜  shogun git:(master) ✗ nosetests --with-coverage --cover-package=api
nose.plugins.cover: ERROR: Coverage not available: unable to import coverage module
E
======================================================================
ERROR: Failure: ImportError (No module named flask.ext.testing)
```

**Comment by rodowi** [comment]
Parece que en general, los dev-requirements no se instalan:

```bash
(shogun)➜  shogun git:(master) pip install -r dev-requirements.txt 
Downloading/unpacking Flask-Testing==0.4.2 (from -r dev-requirements.txt (line 1))
  Downloading Flask-Testing-0.4.2.tar.gz (40kB): 40kB downloaded
  Running setup.py egg_info for package Flask-Testing
    
    warning: no previously-included files matching '*.pyc' found under directory 'tests'
    warning: no previously-included files matching '*.pyc' found under directory 'tests'
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
    no previously-included directories found matching 'docs/_build'
    no previously-included directories found matching 'docs/_themes/.git'
Downloading/unpacking PyYAML==3.11 (from -r dev-requirements.txt (line 2))
  Downloading PyYAML-3.11.tar.gz (248kB): 248kB downloaded
  Running setup.py egg_info for package PyYAML
    
Downloading/unpacking astroid==1.3.8 (from -r dev-requirements.txt (line 3))
  Downloading astroid-1.3.8.tar.gz (155kB): 155kB downloaded
  Running setup.py egg_info for package astroid
    
Downloading/unpacking coverage==3.7.1 (from -r dev-requirements.txt (line 4))
  Downloading coverage-3.7.1.tar.gz (284kB): 284kB downloaded
  Running setup.py egg_info for package coverage
    
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
Downloading/unpacking coveralls==0.5 (from -r dev-requirements.txt (line 5))
  Downloading coveralls-0.5.zip
  Running setup.py egg_info for package coveralls
    
Requirement already satisfied (use --upgrade to upgrade): docopt==0.6.2 in /Users/rodolfo/.virtualenvs/shogun/lib/python2.7/site-packages (from -r dev-requirements.txt (line 6))
Downloading/unpacking funcsigs==0.4 (from -r dev-requirements.txt (line 7))
  Downloading funcsigs-0.4.tar.gz
  Running setup.py egg_info for package funcsigs
    
Downloading/unpacking logilab-common==1.0.2 (from -r dev-requirements.txt (line 8))
  Downloading logilab-common-1.0.2.tar.gz (190kB): 190kB downloaded
  Running setup.py egg_info for package logilab-common
    
    warning: no files found matching '*.py' under directory 'test/input'
    warning: no files found matching '*' under directory 'doc/html'
Downloading/unpacking mock==1.3.0 (from -r dev-requirements.txt (line 9))
  Downloading mock-1.3.0.tar.gz (70kB): 70kB downloaded
  Running setup.py egg_info for package mock
    mock requires setuptools>=17.1. Aborting installation
    Complete output from command python setup.py egg_info:
    mock requires setuptools>=17.1. Aborting installation

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /Users/rodolfo/.virtualenvs/shogun/build/mock
Storing complete log in /Users/rodolfo/.pip/pip.log
(shogun)➜  shogun git:(master) nosetests --with-coverage --cover-package=api
nose.plugins.cover: ERROR: Coverage not available: unable to import coverage module
E
======================================================================
ERROR: Failure: ImportError (No module named flask.ext.testing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rodolfo/anaconda/lib/python2.7/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/rodolfo/anaconda/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/rodolfo/anaconda/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/rodolfo/c/shogun/api/v1/tests/tests.py", line 1, in <module>
    from flask.ext.testing import TestCase
  File "/Users/rodolfo/anaconda/lib/python2.7/site-packages/flask/exthook.py", line 87, in load_module
    raise ImportError('No module named %s' % fullname)
ImportError: No module named flask.ext.testing

----------------------------------------------------------------------
Ran 1 test in 0.081s

FAILED (errors=1)
(shogun)➜  shogun git:(master) pip list | grep test
(shogun)➜  shogun git:(master) pip list | grep Test
(shogun)➜  shogun git:(master) 
```

**Comment by urkonn** [comment]
parece que es problema de anaconda 
http://stackoverflow.com/questions/21465151/install-module-using-pip-within-anaconda-environment

**Comment by rodowi** [comment]
pero estoy en virtual env

(shogun)➜  shogun git:(update-organizations) which pip
/Users/rodolfo/.virtualenvs/shogun/bin/pip

**Comment by rodowi** [comment]
Temporalmente lo arreglé usando otra consola sin virtualenv e instalando globalmente las dependencias.

Este issue no se cierra, pero le bajo prioridad porque puedo seguir trabajando.
