### ISSUE TITLE
Problem running `heroku local`

### ISSUE THREAD

**Issue by iorch** [mxabierto/shogun#32]
forego | starting web.1 on port 5000
web.1  | [2015-11-24 13:34:33 -0600] [66619] [INFO] Starting gunicorn 19.3.0
web.1  | [2015-11-24 13:34:33 -0600] [66619] [INFO] Listening at: http://0.0.0.0:5000 (66619)
web.1  | [2015-11-24 13:34:33 -0600] [66619] [INFO] Using worker: sync
web.1  | [2015-11-24 13:34:33 -0600] [66647] [INFO] Booting worker with pid: 66647
web.1  | [2015-11-24 13:34:33 -0600] [66648] [INFO] Booting worker with pid: 66648
web.1  | [2015-11-24 13:34:33 -0600] [66649] [INFO] Booting worker with pid: 66649
web.1  | [2015-11-24 13:34:33 -0600] [66647] [ERROR] Exception in worker process:
web.1  | mxabierto/shogun/api/app.py", line 5, in <module>
web.1  | py", line 118, in init_process
web.1  | ages/ckanapi/remoteckan.py", line 44, in __init__
web.1  | [2015-11-24 13:34:33 -0600] [66647] [INFO] Worker exiting (pid: 66647)
web.1  | [2015-11-24 13:34:33 -0600] [66648] [ERROR] Exception in worker process:
web.1  | mxabierto/shogun/api/app.py", line 5, in <module>
web.1  | py", line 118, in init_process
web.1  | ages/ckanapi/remoteckan.py", line 44, in __init__
web.1  | [2015-11-24 13:34:33 -0600] [66648] [INFO] Worker exiting (pid: 66648)
web.1  | Traceback (most recent call last):
web.1  |     sys.exit(run())
web.1  |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
web.1  |   File "/Users/iorch/.pyenv/versions/2.7.10/lib/python2.7/site-packages/gunicorn/app/base.py", line 189, in run
web.1  |     super(Application, self).run()
web.1  |   File "/Users/iorch/.pyenv/versions/2.7.10/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
web.1  |     Arbiter(self).run()
web.1  |     self.manage_workers()
web.1  |   File "/Users/iorch/.pyenv/versions/2.7.10/lib/python2.7/site-packages/gunicorn/arbiter.py", line 477, in manage_workers
web.1  |     self.spawn_workers()
web.1  |   File "/Users/iorch/.pyenv/versions/2.7.10/lib/python2.7/site-packages/gunicorn/arbiter.py", line 541, in spawn_workers
web.1  |     time.sleep(0.1 * random.random())
web.1  |   File "/Users/iorch/.pyenv/versions/2.7.10/lib/python2.7/site-packages/gunicorn/arbiter.py", line 214, in handle_chld
web.1  |     self.reap_workers()
web.1  |   File "/Users/iorch/.pyenv/versions/2.7.10/lib/python2.7/site-packages/gunicorn/arbiter.py", line 459, in reap_workers
web.1  |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
web.1  | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
web.1  | Exception gunicorn.errors.HaltServer: HaltServer() in <module 'threading' from '/Users/iorch/.pyenv/versions/2.7.10/lib/python2.7/threading.pyc'> ignored
web.1  | [2015-11-24 13:34:33 -0600] [66649] [ERROR] Exception in worker process:
web.1  | mxabierto/shogun/api/app.py", line 5, in <module>
web.1  | py", line 118, in init_process
web.1  | ages/ckanapi/remoteckan.py", line 44, in __init__
web.1  | [2015-11-24 13:34:33 -0600] [66649] [INFO] Worker exiting (pid: 66649)

**Comment by iorch** [comment]
resuelto
