### ISSUE TITLE
Failure: datacats create your-instance

### ISSUE THREAD

**Issue by rodowi** [mxabierto/shogun#35]
```bash
(ckan)➜  c  datacats create catstown
Creating environment "catstown/primary"../Users/rodolfo/.virtualenvs/ckan/lib/python2.7/site-packages/docker/utils/utils.py:486: UserWarning: docker.utils.create_host_config() is deprecated. Please use Client.create_host_config() instead.
  'docker.utils.create_host_config() is deprecated. Please use '
...
----------------------------------------
datacats: problem was encountered:
Something that should not have happened happened when attempting to run this command:
     datacats create catstown

It is seems to be a bug.
Please report this issue to us by creating an issue ticket at

    https://github.com/datacats/datacats/issues

so that we would be able to look into that and fix the issue.

------------------------------
Please quote this traceback when reporting this error:
Traceback (most recent call last):
  File "/Users/rodolfo/.virtualenvs/ckan/lib/python2.7/site-packages/datacats/cli/main.py", line 92, in main
    return command_fn(opts)
  File "/Users/rodolfo/.virtualenvs/ckan/lib/python2.7/site-packages/datacats/cli/create.py", line 62, in create
    init_db=not opts['--no-init-db'],
  File "/Users/rodolfo/.virtualenvs/ckan/lib/python2.7/site-packages/datacats/cli/create.py", line 104, in create_environment
    fn()
  File "/Users/rodolfo/.virtualenvs/ckan/lib/python2.7/site-packages/datacats/environment.py", line 303, in create_ckan_ini
    ro={scripts.get_script_path('run_as_user.sh'): '/scripts/run_as_user.sh'},
  File "/Users/rodolfo/.virtualenvs/ckan/lib/python2.7/site-packages/datacats/environment.py", line 853, in run_command
    commit=True, stream_output=stream_output)
  File "/Users/rodolfo/.virtualenvs/ckan/lib/python2.7/site-packages/datacats/docker.py", line 178, in web_command
    volumes_from=volumes_from)
  File "/Users/rodolfo/.virtualenvs/ckan/lib/python2.7/site-packages/docker/utils/decorators.py", line 21, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/Users/rodolfo/.virtualenvs/ckan/lib/python2.7/site-packages/docker/api/container.py", line 343, in start
    self._raise_for_status(res)
  File "/Users/rodolfo/.virtualenvs/ckan/lib/python2.7/site-packages/docker/client.py", line 142, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
APIError: 500 Server Error: Internal Server Error ("Cannot start container 48267411ff0f206e1ef7b8ceb6a92f4da3ebd0743ebb8c1d416e98300154860c: [8] System error: exec: "/scripts/run_as_user.sh": permission denied")
```

**Comment by rodowi** [comment]
una pista en https://github.com/datacats/datacats/issues/4

(ckan)➜  c  docker logs thirsty_wozniak
exec: "/scripts/run_as_user.sh": permission denied
(ckan)➜  c

**Comment by rodowi** [comment]
Lo resuelven acá https://github.com/datacats/datacats/issues/83, pero no sé donde está la carpeta scripts que mencionan.
